### PR TITLE
RFC: Support for exceptions with cake > 3.3 middleware

### PR DESCRIPTION
**Pull request by Spriz**
Not sure what you think of this? We have it internally in our app but might share it even though it's very short. 

At least it gives people an idea on how to solve it if they see no exceptions with middleware - so maybe it should rather be a code snippet in the readme describing you can do this?

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks!

**Comment by lorenzo** [comment]
@Spriz can you maybe add some docs to the readme for using this?

**Comment by Spriz** [comment]
Sure can @lorenzo!

**Comment by Spriz** [comment]
I completely forgot about this - done now @lorenzo

**Pull request merged**
